path: /home/robiotec/Documents/Entrenamientos/Training/data/TENGEL/M93/split/m93_split_35mm_partial_representative_v1
train: train/images
val: val/images
test: test/images

nc: 2
names:
  0: caja
  1: caja_cachito
