train: /home/robiotec/TENGEL/dataset_split_caja_veta/train
val: /home/robiotec/TENGEL/dataset_split_caja_veta/val
test: /home/robiotec/TENGEL/dataset_split_caja_veta/test
# Number of classes
nc: 2
# Class names
names: ['Caja', 'Veta'] # class 0=Caja, class 1=Veta
