train: /home/robiotec/TENGEL/dataset_split_veta/train
val: /home/robiotec/TENGEL/dataset_split_veta/val
test: /home/robiotec/TENGEL/dataset_split_veta/test
# Number of classes
nc: 1
# Class names
names: ['vetas']
